### PR TITLE
Fix for the now deprecated brower option parameter

### PR DESCRIPTION
**Pull request by ghost**
The browser option parameter `f'{driver_name}_options'` has been deprecated in [Selenium 3.8.0](https://github.com/SeleniumHQ/selenium/blob/5561cda968e2c392b350e9a1c40bb381491f58a6/py/CHANGES#L375).

Browser option parameters are now standardized across drivers as `options`. `firefox_options`, `chrome_options`, and `ie_options` are now deprecated.

### CODE REVIEW

**Review by ANarayanan-Cervello — APPROVED** [review]
This change is highly needed as '{driver_name}_options' for all browsers have been standardized into one Options class.

**Comment by ghost** [comment]
Yes but unfortunately it looks like this repo is no longer being maintained.
I would be happy to share a few more improvements/fixes but I don't think it's worth the effort as long as we don't know about the becoming of this project.

**Comment by ANarayanan-Cervello** [comment]
Hey @zacharyarnaise I would like to have this change packaged into a library ,and hosted on a repo, so that I could build  it from there. Would it be possible for you to do that?

**Comment by ghost** [comment]
I wouldn't mind, what dependency/packaging management tool are you using?
I know for instance that [Poetry](https://github.com/python-poetry/poetry) allows one to add git dependencies, it might be easier than hosting my repo for such a small change.

**Comment by ANarayanan-Cervello** [comment]
@zacharyarnaise I wouldn't mind anything, as long as there are instructions that tell me how to do it. However I would prefer pip. To give an idea ,I am using a conda virtual environment ,and use both pip and conda commands for pulling modules. Recently I tried building from repo by doing "pip install https://github.com/user/repo.git@branch" .

**Pull request closed without merging**
