### PR TITLE
Script parameter

### PR DESCRIPTION
**Pull request by j4n7**
Sorry I took me such long time, I have been working on some other projects. As simple as the title says, this is useful when some content in webpages is not displayed unless you do an especific acction like scrolling.
I algo expanded the readme to include the changes, hope you like it. I tested it and it works.

### CODE REVIEW

**Comment by j4n7** [comment]
Ok, I can try that, but I have never worked with this kind of tests so I don't know If I will be able to do it.

**Comment by j4n7** [comment]
Ok, I thik I did it. Maybe you can have a quick look to see if there is something wrong. I ran the test on my computer an everything seems fine but because I'm very new to this maybe I made some mistakes.

**Comment by clemfromspace** [comment]
Perfect, this is exactly what I was thinking about 👌

**Comment by clemfromspace** [comment]
@j4n7 Released the 0.0.7 with the `script` parameter: https://pypi.org/project/scrapy-selenium/

Thanks again for your contribution!

**Pull request merged**
